name: Install dependencies
on:
    workflow_dispatch:
    push:
        branches: main
        paths:
            - package.json
            - package-lock.json
    schedule:
        - cron: "0 0 */6 * * "

jobs:
    run:
        name: Install dependencies
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              if: !cancelled()
              uses: actions/checkout@main
              with:
                  ref: ${{github.head_ref}}
                  token: ${{secrets.WGYTBOT}}

            - name: Setup Node.JS
              if: !cancelled()
              uses: actions/setup-node@main
              with:
                  node-version: 12.22.1

            - name: Remove
              if: !cancelled()
              run: rm package-lock.json

            - name: Install
              if: !cancelled()
              run: npm install

            - name: Commit
              if: !cancelled()
              id: commit
              uses: stefanzweifel/git-auto-commit-action@master
              with:
                  commit_message:
                      "Install dependencies to prevent deduplication"
                  branch: main
                  commit_options: "--signoff"
                  commit_user_name: wgytbot
                  commit_user_email: 83586655+wgytbot@users.noreply.github.com
                  commit_author:
                      wgytbot <83586655+wgytbot@users.noreply.github.com>

            - name: Repository Dispatch
              if: !cancelled()
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{secrets.WGYTBOT}}
                  repository: ${{ github.repository }}
                  event-type: lint
